version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=kutt
      - POSTGRES_PASSWORD=kutt
    ports:
      - '127.0.0.1:5431:5432'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db